### ISSUE TITLE
App freezes when too much data is written to stdout (in one runloop iteration?)

### ISSUE THREAD

**Issue by mallman** [ActuallyTaylor/HydrogenReporter#1]
Hello,

Thank you for Hydrogen Reporter. This is just what I'm looking for.

I'm running into some serious trouble when my app writes to stdout (using Swift's `print()` function) concurrently from multiple threads. Though the app freezes, I don't think it's concurrency that's causing the problem.

I've been able to reduce the problematic code to a single line:

https://github.com/ActuallyTaylor/HydrogenReporter/blob/3813325c27674e4aec6b1029e9d4df3e03984700/Sources/HydrogenReporter/Backbone/Logger.swift#L225

If I comment out this line, my app does not freeze. If I leave it in, my app freezes. Of course, commenting out that line of code breaks the stdout duplication.

Even if I comment out all other code related to to that line:

https://github.com/ActuallyTaylor/HydrogenReporter/blob/3813325c27674e4aec6b1029e9d4df3e03984700/Sources/HydrogenReporter/Backbone/Logger.swift#L227-L240

it still freezes.

I've tried resolving this issue myself, without success. I hope you can help figure this one out.

Thanks.

**Comment by mallman** [comment]
I'll also note I haven't had this problem with stderr, but that may just be because I'm not writing to stderr concurrently.

**Comment by ActuallyTaylor** [comment]
I’m happy that the the product is exactly what you’re looking for!

This is an interesting issue, I can definitely look more into it and get it resolved.

To help out, do you have any simplified code that causes this issue?

**Comment by mallman** [comment]
> I’m happy that the the product is exactly what you’re looking for!
> 
> This is an interesting issue, I can definitely look more into it and get it resolved.
> 
> To help out, do you have any simplified code that causes this issue?

I do not ATM. However, let me see what I can put together...

**Comment by mallman** [comment]
So the issue actually has nothing to do with concurrency. I can reproduce the app freeze just by printing enough data on the main thread.

Now it looks like the issue has something to do with buffering. I'm guessing some buffer is getting full, and it needs to be read and flushed or the thread blocks.

I will upload a sample app shortly. It's called Hydrogen Bomb 😆.

**Comment by mallman** [comment]
Here's my app:

https://github.com/mallman/HydrogenBomb

I've actually only torn out `Logger.swift` from HydrogenReporter. I needed to do that to fiddle with it. If you do a diff on your source class, you will see two lines difference. (Sorry for the annoyance.)

The most significant difference is at

https://github.com/mallman/HydrogenBomb/blob/2af959e6239223cd795af01c644f6d43503c75fc/HydrogenBomb/Logger.swift#L222

If you uncomment that line, the app does not freeze anymore, however the output is buffered. That's not optimal either.

Note the comment at

https://github.com/mallman/HydrogenBomb/blob/master/HydrogenBomb/HydrogenBomb.swift#L23-L25

is key to triggering (or not) this issue. At least on my computer, an M1 running Ventura 13.5, the conditions stated for triggering or not triggering the issue are valid.

I hope you are able to reproduce the issue on your Mac. If not, try increasing the number of iterations in the loop.

Let me know if I can help in any other way.

Thank you.

**Comment by ActuallyTaylor** [comment]
Thank you a ton for all of this! I will check out HydrogenBomb (love the name 😍) and figure out a way to stop the deadlock from occurring.

**Comment by ActuallyTaylor** [comment]
Okay I have been messing with this for an hour ago and I think you are 100% correct about maxing out the buffer for STDOUT. I think the solution here is going to do with either expanding the buffer for STDOUT or working in a solution to flush when the buffer is full. I will do some more research to find a solution.

**Comment by mallman** [comment]
Hi Taylor,

Have a look at this commit:

https://github.com/mallman/HydrogenBomb/commit/b1616df7a674a041eeb948a86066d1d2b615eed9

I believe this addresses the underlying issue. The original code is trying to read from the same thread (Main) as it is writing. While the main thread is writing in the write loop, the pipe is not being drained. Its buffer becomes full and the writer can no longer write anymore. Meanwhile, the code that's supposed to be draining the pipe is not running because it's running on the main thread. Hence the blocking on IO.

The solution I've taken here is to run the pipe reading code on its own private thread. It can make progress draining the pipe while any other thread is writing. Updates to the published properties are still performed on the main thread—after the main thread completes its current run through the runloop.

Let me know if this sounds right to you. If you agree, I don't believe a PR is necessary. You can make the code changes just by looking at my commit.

Cheers.

(BTW, I verified this worked with stderr as well using [this technique](https://stackoverflow.com/a/41679101) for writing to stderr.)

**Comment by ActuallyTaylor** [comment]
> I believe this addresses the underlying issue. The original code is trying to read from the same thread (Main) as it is writing. While the main thread is writing in the write loop, the pipe is not being drained. Its buffer becomes full and the writer can no longer write anymore. Meanwhile, the code that's supposed to be draining the pipe is not running because it's running on the main thread. Hence the blocking on IO.

This really looks great! I will get this threaded implementation added into main. Thank you a ton for the research that you did to figure this out. From the research I did, this seems like a good solution to the clogged pipe issue that seemed to have been causing this.

**Comment by ActuallyTaylor** [comment]
This has been implemented into the main branch of the repository with the commit b0fece63be918f5b3afe3b1411b6bc66cbe5ff6c.
